domain_path: C:\work\github\FPGA_study\AXI4-Lite_BRAM_SW\AXI4-Lite_BRAM_platform\export\AXI4-Lite_BRAM_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
