domain_path: C:\work\github\FPGA_study\UART\UART_Hello_World\UART_Hello_World_HW\export\UART_Hello_World_HW\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
