domain_path: C:\work\github\FPGA_study\UART\UART_Hello_World\UART_Hello_World_HW\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
