vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xilinx_vip
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/axi_infrastructure_v1_1_0
vlib modelsim_lib/msim/axi_vip_v1_1_21
vlib modelsim_lib/msim/processing_system7_vip_v1_0_23
vlib modelsim_lib/msim/xlconstant_v1_1_10
vlib modelsim_lib/msim/proc_sys_reset_v5_0_17
vlib modelsim_lib/msim/smartconnect_v1_0
vlib modelsim_lib/msim/axi_register_slice_v2_1_35
vlib modelsim_lib/msim/gigantic_mux
vlib modelsim_lib/msim/xlconcat_v2_1_7

vmap xilinx_vip modelsim_lib/msim/xilinx_vip
vmap xpm modelsim_lib/msim/xpm
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap axi_infrastructure_v1_1_0 modelsim_lib/msim/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_21 modelsim_lib/msim/axi_vip_v1_1_21
vmap processing_system7_vip_v1_0_23 modelsim_lib/msim/processing_system7_vip_v1_0_23
vmap xlconstant_v1_1_10 modelsim_lib/msim/xlconstant_v1_1_10
vmap proc_sys_reset_v5_0_17 modelsim_lib/msim/proc_sys_reset_v5_0_17
vmap smartconnect_v1_0 modelsim_lib/msim/smartconnect_v1_0
vmap axi_register_slice_v2_1_35 modelsim_lib/msim/axi_register_slice_v2_1_35
vmap gigantic_mux modelsim_lib/msim/gigantic_mux
vmap xlconcat_v2_1_7 modelsim_lib/msim/xlconcat_v2_1_7

vlog -work xilinx_vip  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"C:/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm  -93  \
"C:/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ipshared/db45/src/fsm_counter_test.v" \
"../../../bd/design_1/ipshared/db45/src/myip_v1_0.v" \
"../../../bd/design_1/ipshared/db45/src/myip_v1_0_S00_AXI.v" \
"../../../bd/design_1/ipshared/db45/src/true_sync_dpbram.v" \
"../../../bd/design_1/ipshared/db45/src/lab13_matbi.v" \
"../../../bd/design_1/ip/design_1_lab13_matbi_0_0/sim/design_1_lab13_matbi_0_0.v" \

vlog -work axi_infrastructure_v1_1_0  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_21  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_23  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/sim/bd_afc3.v" \

vlog -work xlconstant_v1_1_10  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/sim/bd_afc3_one_0.v" \

vcom -work proc_sys_reset_v5_0_17  -93  \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib  -93  \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/sim/bd_afc3_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/sim/bd_afc3_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/sim/bd_afc3_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/sim/bd_afc3_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/sim/bd_afc3_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/sim/bd_afc3_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/sim/bd_afc3_srn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/sim/bd_afc3_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/sim/bd_afc3_swn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/sim/bd_afc3_sbn_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/sim/bd_afc3_m00s2a_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/sim/bd_afc3_m00e_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work axi_register_slice_v2_1_35  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/sim/design_1_axi_smc_0.sv" \

vcom -work xil_defaultlib  -93  \
"../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/sim/bd_f60c.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/sim/bd_f60c_ila_lib_0.v" \

vlog -work gigantic_mux  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/b2b0/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0_gigantic_mux.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/sim/bd_f60c_g_inst_0.v" \

vlog -work xlconcat_v2_1_7  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/9c1a/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../AXI4-lite_BRAM_HW.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_2/sim/bd_f60c_slot_0_aw_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_3/sim/bd_f60c_slot_0_w_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_4/sim/bd_f60c_slot_0_b_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_5/sim/bd_f60c_slot_0_ar_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_6/sim/bd_f60c_slot_0_r_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/sim/design_1_system_ila_0_0.v" \
"../../../bd/design_1/sim/design_1.v" \

vlog -work xil_defaultlib \
"glbl.v"

